name: flutter_headset_detector
description: Flutter Plugin for headset events. Detect headset is plugged and unplugged. Get current headset state.
version: 3.1.0
homepage: https://github.com/turlvo/flutter_headset_detector

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.13

flutter:
  plugin:
    platforms:
      android:
        package: flutter.moum.flutter_headset_detector
        pluginClass: FlutterHeadsetDetectorPlugin
      ios:
        pluginClass: FlutterHeadsetDetectorPlugin
